# Generated by Django 6.0.3 on 2026-03-31 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.IntegerField(unique=True, verbose_name="Код пункта выдачи"),
                ),
                ("address", models.CharField(max_length=500, verbose_name="Адрес")),
            ],
            options={
                "verbose_name": "Пункт выдачи",
                "verbose_name_plural": "Пункты выдачи",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="pickup_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.pickuppoint",
                verbose_name="Пункт выдачи",
            ),
        ),
    ]
